2/index.php

There is an important client library for Python missing. Even if I'am only a consumer of the library and not related to the author in any kind, I like to thank the author Peter Hudec and contribute a line with a link.

Add Authomatic Python OAuth2 client library

---

2/index.php
code/index.php

scribe-java have been migrated to the new place (https://github.com/scribejava/scribejava).
The old link (currently on the site) https://github.com/fernandezpablo85/scribe-java is actualy redirecting to the new URL.
Ownership of the project was transfered to the new developer as well.

update info about ScribeJava library

---

2/index.php

SSQ singon in an OAuth 2.0 server as a service. Supports all grant types except implicit. For more info please visit https://ssqsignon.com

Added SSQ signon to the list of proxy services.

---

grant_type/1.0.html

Describes what this URI is used for.

Added a basic page for the http://oauth.net/grant_type/device/1.0 grant type value.

---

1/index.php
code/index.php

Hi,
I noticed that the site structure has changed a bit since I submitted my first PR https://github.com/aaronpk/oauth.net/pull/90/files about Grant.
Grant is OAuth1 client and OAuth2 authorization_code client middleware for NodeJS, supporting Express, Koa and Hapi.
I updated the existing information for OAuth1, and added the library to the code section for OAuth2.
The showcase application can be found here: https://grant.outofindex.com

Update Grant info for OAuth1 and add it to the code section for OAuth2

---

code/index.php

gin-oauth2 (https://github.com/zalando/gin-oauth2) is open-source Golang middleware for Gin Framework users who also want to use OAuth2.

Added gin-oauth2 to the "Server Libraries"/Golang

---

code/index.php

- rename `Golang` to `Go`
- remove https://github.com/golang/oauth2 from listed clients as it is only alias for `golang.org/x/oauth2` that is already mentioned

Cleanup Go links

---

code/index.php

Hydra itself is a on-prem server (docker, binary, or from src) so I added it to the "proxy services" section and added fosite (go server library) to the go server section. Also added osin to the list.

docs/code: updated golang and proxy services

---

2/index.php

This PR adds reference to [RFC 7009: OAuth 2.0 Token Revocation](https://tools.ietf.org/html/rfc7009) to _OAuth 2.0 Extensions_ resources.

Add reference to RFC 7009

---

code/index.php

This is done to create less confusion. Only the description of library looked ambiguous.

Added name of the Rust client library

---

workshop/next/index.php

At https://sec.uni-stuttgart.de/events/osw2019, we will soon publish more information and the registration for the next OAuth Security Workshop, which in 2019 will be held at the University of Stuttgart, Germany. It would be great to create a short URL to the conference page, and update it for the workshops in the next years.

Create short URL for the OAuth Security Workshop

---

code/data.php

Add FastAPI to OAuth2 servers :smile: 
FastAPI has utilities to handle all the OAuth2 flows in the server side, integrated with OpenAPI. Including the definition of scopes per route.

Add FastAPI to OAuth2 servers

---

tests/EventTest.php

The test now uses a data provider that will feed it the JSON object as well as the file path. The latter is not strictly necessary but is used for the error messages.
This means all JSON files will be checked when the test runs so all errors can be fixed in one go, rather than the test stopping at the first failure.
Example run where a letter slipped into the date:
```
PHPUnit 8.0.4 by Sebastian Bergmann and contributors.
.........F.......                                                 17 / 17 (100%)
Time: 52 ms, Memory: 4.00 MB
There was 1 failure:
1) EventTest::testJSONFileSyntax with data set "internet-identity-workshop-xxvii.json" (array('Internet Identity Workshop XXVII', '2018-10-a23', '2018-10-25', 'Computer History Museum, Moun...fornia', …
```

Use PHPUnit Data Providers to run the test once for every data file

---

code/index.php

I updated the ORY Hydra URL from GitHub to ory.sh/hydra which is more representative than the GitHub page (has docs, github, forum, chat, ...).

Updated ORY Hydra URL

---

code/index.php

This patch closes #203 by distinguishing between commercial and open source OAuth 2.0 offerings. This hopefully clarifies developers researching the topic on what's what and helps them quickly choose a category that works for them and research the software or commercial offering behind it.

Distinguish between commercial and open source

---

code/data.php

- Replace the "Spring Security OAuth" with the "Spring Security" project: OAuth client functionality has moved to this project.
- Remove the "Spring Security OAuth" project from the list of servers: this functionality has been deprecated.
- Add the Nimbus library as client and server.
- Update "Spring Social" project URL.

Update java implementations

---

3/index.php

Very small letter shuffling :)

Typo on /about for OAuth 3 page

---

videos/index.php

This commit will add a link to a collection of OAuth courses (free and paid) from popular providers like Udemy, Skillshare, Pluralsight and Udacity (and many others to come). Classpert is a search and comparison site for online courses that aims to organize the chaotic online course landscape on the internet. Classpert is 100% free from a user standpoint
_disclaimer: If you believe this isn't the appropriate space for adding this type of link feel free to refuse my PR and suggesting other directions and alternatives_

Add OAuth courses from multiple popular providers via Classpert

---

2/grant-types/password/index.php

This adds a link to the oauth.com documentation for the Password Grant flow, like there is for https://oauth.net/2/grant-types/authorization-code/ and https://oauth.net/2/grant-types/client-credentials/.

Add link to oauth.com documentation for Password Grant

---

1/index.php

Both GO packages by mistake link to the same URL.

Fix the URL for the GO OAuth1 package

---

2.1/index.php

The link was introduced in 95400210509b081cb0592a836e948e7f7e6556ee.

Fix the link to Lee's article

---

code/data.php

Flask-OAuthlib has a notice to use Authlib instead: https://github.com/lepture/flask-oauthlib/blob/master/README.rst#notice.

Remove Flask-OAuthlib from a Python server libs

---

code/index.php

I'm the maintainer of Osso, an open source service that handles SAML SSO against enterprise Identity Providers and makes those users available to a developer via an OAuth 2.0 authorization flow. We sorta wrap SAML (which requires a per-instance configuration) in OAuth 2.0, which makes adding SSO a lot easier for an engineering team.
I hope this is a welcome addition, but admittedly perhaps not 🤞 
You can learn more at https://ossoapp.com or https://github.com/enterprise-oss/osso

Add Osso to open source

---

1/index.php

Recently, as a result of open-sourcing some of my code in an academic project, I made an OAuth1.0 consumer library for Java, named oauth1-hmac (https://github.com/omarathon/oauth1-hmac). It's a very lightweight library wrapping Google's OAuth Client Library for Java (https://developers.google.com/api-client-library/java/google-oauth-java-client), piecing together the APIs in Google's library to provide a simple API for a generic OAuth1.0 consumer. Note: it only works with the HMAC signing strategy.
I figured it may be handy for someone if they're having to interface with a legacy OAuth1.0 provider, and are wanting to get going quickly. Personally I struggled implementing the consumer for my application, so I'm sharing the work in a generic form to hopefully prevent another person's …

Add oauth1-hmac as an OAuth1.0 Java Library

---

code/data.php

There are lots of folks confused with the Qt-provided examples for doing Google SSO authentication with their native desktop apps using Qt. This PR adds a link to a discussion of the issue, and a workaround until Qt fixes the problem.

Mention problems with Qt when doing Google SSO

---

articles/index.php

This patch adds an article to the article list which explains how to set up the popular open source OAuth2 Server ORY Hydra.

Add guide for setting up open source OAuth2 Server

---

public/about/introduction/index.php

The link target seems to be down. Article was tracked down to its new location.

Fixed broken link

---

public/2/grant-types/index.php

This aligns the Grant Types index page with the top-level index page.

Add PKCE link to the Grant Types index

---

public/2/pkce/index.php

Although PKCE makes it *more* secure, it does not enable secure OAuth exchange from public clients.
This misinformation leads to misunderstandings like 
> ["TLDR: The PKCE flow is a secure way to authenticate public clients."](https://kevcodez.de/posts/2020-06-07-pkce-oauth2-auth-flow-cli-desktop-app/)
And other examples described in https://www.scottbrady91.com/oauth/client-authentication-vs-pkce

Remove insecure statement for public clients

---

public/1/index.php

- 🐛  Fix dead link for Blaine Cook
- 📝. Note that Blaine was co-author of the specification

📝  Add Maintaner - Ruby

---

data/code/ruby.yml

- remove reference to archived-for-12-years-now `oauth2-server` gem

Fix URL for oauth2 gem

---

public/code/index.php

About Omejdn:
"Omejdn" is bavarian for "Log In". The Server written in Ruby tries to support both OAuth 2.0/2.1 and OpenID Connect while following the Security BCP, along with many current features such as Server Metadata, JWT Access Tokens, Pushed Authorization Requests, ...
It currently does not support Dynamic Client Registration and Management.
It tries to maintain a minimal code base and to be easily extensible, making it suitable as a base for research projects.

Add Omejdn to Open Source Authorization Servers

---

data/code/ruby.yml

[rodauth-oauth](https://gitlab.com/honeyryderchuck/rodauth-oauth) builds on top of the rodauth authentication framework to provide an easy extensible way to build OAuth an OIDC authorization servers.

Adding rodauth-oauth to the list

---

public/code/index.php

Hi - We migrated zitadel from caos/zitadel to zitadel/zitadel.

docs: change org name for zitadel

---

public/1/index.php

Also correct my typo in anchor attributes: href != src
See notice posted at https://github.com/oauth-xx/oauth-ruby

oauth gem has moved to Gitlab

---

data/code/python.yml

- Removed the following references to unmaintained projects
- https://github.com/TransparentHealth/hhs_oauth_server
- https://github.com/NateFerrero/oauth2lib 
- https://github.com/demianbrecht/sanction
- http://github.com/litl/rauth
- https://github.com/lepture/flask-oauthlib
- Removed references to Python 3

Improve python libraries page

---

public/articles/index.php

From
https://www.loginradius.com/engineering/blog/oauth2/ to
https://www.loginradius.com/blog/engineering/oauth2/

Corrected link to article Getting Started with OAuth 2.0

---

data/code/javascript.yml
data/code/nodejs.yml

The JS lib from Zalando is displayed as not longer maintained: https://github.com/zalando-stups/

Update JS and NodeJS libraries

---

data/code/go.yml

Add link to new go library implementing DPoP.
Feedback on if (not) this belongs here is appreciated.

docs: add go-dpop library

---

data/code/elixir.yml

It would be great to have the library version linked in that page.
Thank you.

Link to library instead of standalone version

---

data/code/nodejs.yml

`oidc-client-ts` is a client library but not OAuth Server library

confusion in nodejs.yml

---

public/2.1/index.php

Version 11 of the Oauth 2.1 spec was marked as "Expired & archived". It was replaced by active version 12.

Update link to OAuth2.1 draft to reference version 12

---

public/2/pkce/index.php

Current docs links to a dead link which redirects to `https://www.loginradius.com/blog/pkce/` which returns with the contents of `You just hit a route that doesn't exist... the sadness.`
Changed the `/blog`around within the URL now redirects to the current page.

Fix loginradius.com link in PKCE docs

---

data/code/ruby.yml

The old org name oauth-xx was intended to make it a suitable host for oauth libraries across multiple languages, but this never materialized.  Since the org only ever catered to ruby it made sense to rename to ruby-oauth.
More on the rename here: https://dev.to/galtzo/rename-oauth-xx-org-to-ruby-oauth-g44

Org name change to ruby-oauth
