aaronpk/oauth.net

2/index.php

Added the HiDrive online storage service to the list of "Services that
support OAuth 2"

Add HiDrive Online Storage

---

code/index.php

Hi guys, :smile:
I correct a link in the `index.php` file. :pencil2: 
Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

Correct link

---

code/index.php

Adding open source project ActionScript OAuth 2, a client library for Flex/Flash/AIR applications to integrate with OAuth 2-compliant services.

Adding OAuth 2 client library for ActionScript

---

2/index.php

Add missed Closing parenthesis in Qt/C++ O2 link

Add missing parenthesis

---

books/index.php

Book Link: http://bit.ly/1UCBQGX

Add 'Mastering OAuth 2.0' by Charles Bihis

---

books/index.php

Hi Aaron.  I'm the author of this book and was hoping to update the text with a better description.  Added some points that would be beneficial to note for readers (namely that the book is client-focused).

Update description text for "Mastering OAuth 2.0" book

---

books/index.php

The layout of the books and book descriptions is not properly aligned.  This commit adds some height to the top book div to alleviate that.  Please consider merging :)

Fix layout of books

---

2/index.php

Hi,
I added Tokens, our open-source Java library for conveniently verifying and storing OAuth 2.0 service access tokens.

Updated page w/new Server Libraries add, "Tokens"

---

2/index.php

These two implementations are built for the amazing Perl web
framework named Mojolicious.

Add Perl implementations

---

includes/_footer.php

Adjusted so that Okta logo is clickable as well

Minor adjustment to footer

---

getting-started/index.php

Fix missing link.

---

code/index.php

Light OAuth2 Server is based on microservices architecture and the fastest and lightest on the market. 
Light Java Client is designed to hide all the interactions with OAuth2 Authorization Server with token renewal, connection pool management and service discovery etc.

Add Light OAuth2 Server and Light Java Client

---

code/index.php

Added HHS OAuth2 Server to list of server implementations

Added HHS OAuth2 Server to list of server implementations

---

code/index.php

Qt supports OAuth 1+2 natively since v5.8

Added Qt Network Authentication entry

---

code/index.php

Xamarin.Auth xplat OAuth library for Xamarin.Android, Xamarin.iOS, UWP, WinRT Windows 8.1, WinRT Windows Phone 8.1, Windows Phone 8 Silverlight.

Xamarin.Auth added

---

code/index.php

Hey!
I've just added an entry for an Elm client library for OAuth 2.0 :)
PS: Elm is awesome.

add Elm client library

---

code/index.php

Added the Curity server to the list of proxy services.

Updated code page with new server

---

code/index.php

Add Perl OAuth2 server.

---

code/index.php

This PR includes an addition to the client code listing page to point to a ColdFusion OAuth2 client library package.

Added ColdFusion client library for CFML applications.

---

1/index.php
code/index.php

Things changed:
1. OAuthlib has moved to https://github.com/oauthlib
2. Added another python implementation

Update OAuthlib link. Add Authlib.

---

code/index.php

Reference: https://attic.apache.org/projects/oltu.html

Removing Apache Oltu from Java clients (moved to Attic)

---

code/index.php

Can you please tell me whether this pull request is okay or not ?

client oauth library by google

---

2/bearer-tokens/index.php

Not sure if it's the right link, but it's the one used in `code/index.php`

Fix jwt link

---

code/index.php

Added IdentityServer4 and changed IdentityServer3 link

Added IdentityServer4 and changed IdentityServer3 link

---

code/index.php

I have added  blizzard's api docs as a service that supports oauth2.

Add blizzard api as service that supports oauth2

---

code/index.php

1. remove HHS OAuth2 Server
2. Python Social Auth is client not server

Remove invalid Python libraries

---

1/index.php

Module link has changed
Should we also update http links to https ?

Update Oauth 1 Go library link

---

code/data.php

Hey @aaronpk 
This adds certified OIDC implementations for both client and provider to the node.js section.

add libraries to https://oauth.net/code/nodejs

---

code/data.php

This Requests-OAuthlib lib is also behind the popular Django lib https://github.com/python-social-auth/social-app-django

Add Requests-OAuthlib into list of Python lib

---

code/data.php

Update the url of the GitHub repo search result.

Updated Mozilla fxa URL

---

code/index.php

Now that SimpleLogin is fully open-source, move it to open-source section

---

code/index.php

Re-ordered Glewlwyd in the list to make it sorted alphabetically as I assume that's the order that is wanted.

Add Keycloak and Red Hat Single Sign-On

---

1/index.php

This is a package for `OAuth1` that follows a similar design to [golang.org/x/oauth2](https://godoc.org/golang.org/x/oauth2).

Add OAuth1 package for Golang

---

code/data.php

Heimdallr is an OAuth 2.0 client specifically designed for easy usage.

Added Heimdallr to swift client libraries

---

code/index.php

Added cidaas to list of OAuth Services (Commercial)

Add cidaas (Cloud Identity & Access Management)

---

2/pkce/index.php

Added PKCE article in more resources listing

Added PKCE article in more resources listing

---

1/index.php
code/data.php

Hi @aaronpk,
I decided to update the description about my OAuth client ([Grant](https://github.com/simov/grant)), let me know if it is too excessive, I tried to outline the key selling points only.
It doesn't look too bad on my end:
Recently I released 4 new serverless handlers for lambda functions, and then also one additional handler for Fastify.

Update description about Grant Node.js module

---

articles/index.php

Added articles related to OAuth 1.0 and OAuth 2.0

Added articles related to OAuth 1.0 and OAuth 2.0

---

articles/index.php

Updated broken link for OAuth 2.0 blog

Updated broken link for OAuth 2.0 blog

---

code/index.php

I felt a little weird/presumptuous putting this at the top; but it appears to be alphabetically sorted.

Add another open source oauth2 server

---

1/index.php
code/render.php

It seems the `master` branch was renamed to `main`

Fix somewhat broken link

---

code/data.php

https://github.com/RangelReale/osin has not been updated in 2.5 years and has been archived

Remove archived library

---

code/data.php

Update link reference to Python Social Auth library documentation.

Update python-social-auth link

---

code/data.php

Introducing Boruta the core of an OAuth 2.0 provider leveraging hexagonal architecture.

Boruta, a new OAuth provider library written in elixir

---

public/2.1/index.php

This page is the first Google result for "oauth 2.1" and I often find myself getting to the draft from here. This PR will save me one whole extra click. 😁

Update OAuth 2.1 draft link to v5

---

data/code/ruby.yml

See notice posted at https://github.com/oauth-xx/oauth2

oauth2 gem has moved to Gitlab

---

public/code/index.php

Added [Authentik](https://goauthentik.io) to OAuth2 provider list.

Add authentik to provider list.

---

public/2/device-flow/index.php
public/2/grant-types/device-code/index.php
public/2/grant-types/index.php
public/articles/index.php

This PR removes or update links when the links have just moved.

chore: remove or update dead links

---

public/code/index.php

Adding Descope to Code Commercial  section

Adding Descope to Code Commercial  section

---

public/2/dpop/index.php
public/2/index.php
public/2/mtls/index.php
public/http-signatures/index.php

DPoP became an official RFC. All references are updated accordingly.

DPoP became RFC 9449

---

data/code/javascript.yml
public/code/index.php

As per the title, also, any clue why https://oauth.net/code/deno/ has a 500 error?

update js data and open source providers

---

data/code/swift.yml

Add new Swift Library

---

public/code/index.php

It would be great if boruta standalone version was listed in the provider section.
Thank you.

Add boruta openid provider

---

public/code/index.php

boruta is open source, then moved to the according section.

move boruta to open source provider

---

public/code/index.php

I added Corbado, a startup similar to Clerk, into the list of Commercial providers. The startup also offers OAuth and other Authentication methods for developers and has a forever-free community plan.

Update index.php: Added Corbado as commercial provider

---

public/security/index.php

Looks like ldapwiki has slightly changed their URLs.

Update index.php - Fix ldapwiki link
